// Generated by gir (https://github.com/gtk-rs/gir @ b5068ede6c51)
// from ../../gir-files (@ 248ad6976459)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) NEMO_OPERATION_COMPLETE);
    PRINT_CONSTANT((gint) NEMO_OPERATION_FAILED);
    PRINT_CONSTANT((gint) NEMO_OPERATION_IN_PROGRESS);
    return 0;
}
