// Generated by gir (https://github.com/gtk-rs/gir @ b5068ede6c51)
// from ../../gir-files (@ 248ad6976459)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "NemoColumnClass", sizeof(NemoColumnClass), alignof(NemoColumnClass));
    printf("%s;%zu;%zu\n", "NemoColumnProviderIface", sizeof(NemoColumnProviderIface), alignof(NemoColumnProviderIface));
    printf("%s;%zu;%zu\n", "NemoColumnProviderInterface", sizeof(NemoColumnProviderInterface), alignof(NemoColumnProviderInterface));
    printf("%s;%zu;%zu\n", "NemoDesktopPreferencesClass", sizeof(NemoDesktopPreferencesClass), alignof(NemoDesktopPreferencesClass));
    printf("%s;%zu;%zu\n", "NemoFileInfoInterface", sizeof(NemoFileInfoInterface), alignof(NemoFileInfoInterface));
    printf("%s;%zu;%zu\n", "NemoInfoProviderIface", sizeof(NemoInfoProviderIface), alignof(NemoInfoProviderIface));
    printf("%s;%zu;%zu\n", "NemoInfoProviderInterface", sizeof(NemoInfoProviderInterface), alignof(NemoInfoProviderInterface));
    printf("%s;%zu;%zu\n", "NemoLocationWidgetProviderIface", sizeof(NemoLocationWidgetProviderIface), alignof(NemoLocationWidgetProviderIface));
    printf("%s;%zu;%zu\n", "NemoLocationWidgetProviderInterface", sizeof(NemoLocationWidgetProviderInterface), alignof(NemoLocationWidgetProviderInterface));
    printf("%s;%zu;%zu\n", "NemoMenuClass", sizeof(NemoMenuClass), alignof(NemoMenuClass));
    printf("%s;%zu;%zu\n", "NemoMenuItemClass", sizeof(NemoMenuItemClass), alignof(NemoMenuItemClass));
    printf("%s;%zu;%zu\n", "NemoMenuProviderIface", sizeof(NemoMenuProviderIface), alignof(NemoMenuProviderIface));
    printf("%s;%zu;%zu\n", "NemoMenuProviderInterface", sizeof(NemoMenuProviderInterface), alignof(NemoMenuProviderInterface));
    printf("%s;%zu;%zu\n", "NemoNameAndDescProviderIface", sizeof(NemoNameAndDescProviderIface), alignof(NemoNameAndDescProviderIface));
    printf("%s;%zu;%zu\n", "NemoNameAndDescProviderInterface", sizeof(NemoNameAndDescProviderInterface), alignof(NemoNameAndDescProviderInterface));
    printf("%s;%zu;%zu\n", "NemoOperationResult", sizeof(NemoOperationResult), alignof(NemoOperationResult));
    printf("%s;%zu;%zu\n", "NemoPropertyPageClass", sizeof(NemoPropertyPageClass), alignof(NemoPropertyPageClass));
    printf("%s;%zu;%zu\n", "NemoPropertyPageProviderIface", sizeof(NemoPropertyPageProviderIface), alignof(NemoPropertyPageProviderIface));
    printf("%s;%zu;%zu\n", "NemoPropertyPageProviderInterface", sizeof(NemoPropertyPageProviderInterface), alignof(NemoPropertyPageProviderInterface));
    printf("%s;%zu;%zu\n", "NemoSimpleButtonClass", sizeof(NemoSimpleButtonClass), alignof(NemoSimpleButtonClass));
    return 0;
}
